# Generated by Django 5.1.6 on 2025-02-15 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='data_pagamento',
        ),
    ]
