# Generated by Django 5.1.6 on 2025-02-15 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_remove_pacientes_data_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='pagamento_em_dia',
        ),
    ]
