# Generated by Django 5.1.6 on 2025-02-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_pacientes_pagamento_em_dia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacientes',
            name='pagamento_em_dia',
            field=models.BooleanField(default=True),
        ),
    ]
