# Generated by Django 5.1.6 on 2025-02-16 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0006_tarefas_consultas'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultas',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultas',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
